GET http://localhost:8080/ HTTP/1.1
###
GET http://localhost:8080/register HTTP/1.1
###
GET http://localhost:8080/login HTTP/1.1
###
GET http://localhost:8080/search HTTP/1.1
###
GET http://localhost:8080/categories HTTP/1.1
###

GET http://localhost:8080/my/ HTTP/1.1
###
GET http://localhost:8080/my/comments HTTP/1.1
###

GET http://localhost:8080/articles/add HTTP/1.1
###
GET http://localhost:8080/articles/1 HTTP/1.1
###
GET http://localhost:8080/articles/edit/1 HTTP/1.1
###
GET http://localhost:8080/articles/category/1 HTTP/1.1
